[gpucpp] in CODEGEN output.py, add run_card_class to avoid crashes after Olivier's commit 8a18cc242 "better handling of the run_card"
  ./MG5_debug:AttributeError: 'PLUGIN_ProcessExporter' object has no attribute 'run_card_class'