[heft] regenerate all processes after trying to use ' '+param.name+' ' in CODEGEN - SUSY processes have changed and fail the build, will need to revert
Example in susy_gg_tt.mad:
ccache g++  -O3  -std=c++17 -I.  -fPIC -Wall -Wshadow -Wextra -ffast-math  -fopenmp  -march=skylake-avx512 -mprefer-vector-width=256  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -c Parameters_MSSM_SLHA2.cc -o Parameters_MSSM_SLHA2.o
In file included from Parameters_MSSM_SLHA2.cc:15:
Parameters_MSSM_SLHA2.h: In function ‘const mg5amcCpu::Parameters_MSSM_SLHA2_dependentCouplings::DependentCouplings_sv mg5amcCpu::Parameters_MSSM_SLHA2_dependentCouplings::computeDependentCouplings_fromG(const fptype_sv&, const double*)’:
Parameters_MSSM_SLHA2.h:829:33: error: ‘mdl_I51x11’ was not declared in this scope
  829 |         out.GC_51 = -( cI * G * mdl_I51x11 );
      |                                 ^~~~~~~~~~

Example in susy_gg_t1t1.mad:
ccache g++  -O3  -std=c++17 -I.  -fPIC -Wall -Wshadow -Wextra -ffast-math  -fopenmp  -march=skylake-avx512 -mprefer-vector-width=256  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -c Parameters_MSSM_SLHA2.cc -o Parameters_MSSM_SLHA2.o
In file included from Parameters_MSSM_SLHA2.cc:15:
Parameters_MSSM_SLHA2.h: In function ‘const mg5amcCpu::Parameters_MSSM_SLHA2_dependentCouplings::DependentCouplings_sv mg5amcCpu::Parameters_MSSM_SLHA2_dependentCouplings::computeDependentCouplings_fromG(const fptype_sv&, const double*)’:
Parameters_MSSM_SLHA2.h:835:33: error: ‘mdl_I51x33’ was not declared in this scope
  835 |         out.GC_55 = -( cI * G * mdl_I51x33 ) - cI * G * mdl_I52x33;
      |                                 ^~~~~~~~~~
Parameters_MSSM_SLHA2.h:835:57: error: ‘mdl_I52x33’ was not declared in this scope
  835 |         out.GC_55 = -( cI * G * mdl_I51x33 ) - cI * G * mdl_I52x33;
      |                                                         ^~~~~~~~~~
Parameters_MSSM_SLHA2.h:836:33: error: ‘mdl_I51x36’ was not declared in this scope
  836 |         out.GC_57 = -( cI * G * mdl_I51x36 ) - cI * G * mdl_I52x36;
      |                                 ^~~~~~~~~~
Parameters_MSSM_SLHA2.h:836:57: error: ‘mdl_I52x36’ was not declared in this scope
  836 |         out.GC_57 = -( cI * G * mdl_I51x36 ) - cI * G * mdl_I52x36;
      |                                                         ^~~~~~~~~~
Parameters_MSSM_SLHA2.h:837:42: error: ‘mdl_I74x33’ was not declared in this scope
  837 |         out.GC_90 = cI * mdl_G__exp__2 * mdl_I74x33 + cI * mdl_G__exp__2 * mdl_I75x33;
      |                                          ^~~~~~~~~~
Parameters_MSSM_SLHA2.h:837:76: error: ‘mdl_I75x33’ was not declared in this scope
  837 |         out.GC_90 = cI * mdl_G__exp__2 * mdl_I74x33 + cI * mdl_G__exp__2 * mdl_I75x33;
      |                                                                            ^~~~~~~~~~