[fvsc] in eemumu mad add an IMPLICIT NONE and remove JAMP2 debug statements
Indeed now NCOLOR no longer builds...

ccache /cvmfs/sft.cern.ch/lcg/releases/gcc/10.2.0-c44b3/x86_64-centos7/bin/gfortran -w -fPIC  -ffixed-line-length-132 -w -cpp  -c -DMG5AMC_MEEXPORTER_CUDACPP auto_dsig1.f -I../../Source/ -fopenmp -o auto_dsig1_cudacpp.o
auto_dsig1.f:584:38:

  584 |           JAMP2_MULTI(0,IVEC) = NCOLOR ! workaround for https://github.com/oliviermattelaer/mg5amc_test/issues/14
      |                                      1
Error: Symbol ‘ncolor’ at (1) has no IMPLICIT type