First simple attempt at OpenMP multi-threading (#82).
The build fails because runTest.exe mixes c++ and cuda objects (#83):

/cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-centos7/bin/g++  -O3 -std=c++11 -I. -I../../src -I../../../../../tools/ -I../../../../../tools//googletest/googletest/include/ -DUSE_NVTX -Wall -Wshadow -fopenmp  -I/usr/local/cuda-11.1/include/ -c runTest.cc -o runTest.o
ln -sf runTest.cc runTest_tmp.cu
/usr/local/cuda-11.1/bin/nvcc -o runTest.exe CPPProcess.o runTest.o gCPPProcess.o runTest_tmp.cu  -O3 -std=c++14 -I. -I../../src -I../../../../../tools/ -I../../../../../tools//googletest/googletest/include/ -I/usr/local/cuda-11.1/include/ -DUSE_NVTX -arch=compute_70 -use_fast_math -lineinfo  -ldl -L../../lib -lmodel_sm -L../../../../../tools//googletest/build/lib// -lgtest -lgtest_main -L/usr/local/cuda-11.1/lib64/ -lcuda -lcurand -lcuda
CPPProcess.o: In function `Proc::sigmaKin(double const*, double*, int) [clone ._omp_fn.0]':
CPPProcess.cc:(.text+0x2312): undefined reference to `omp_get_num_threads'
CPPProcess.cc:(.text+0x2319): undefined reference to `omp_get_thread_num'
CPPProcess.o: In function `Proc::sigmaKin(double const*, double*, int)':
CPPProcess.cc:(.text+0x263f): undefined reference to `GOMP_parallel'
collect2: error: ld returned 1 exit status
make: *** [Makefile:98: runTest.exe] Error 1