[jt774] in gg_tt.mad cudacpp.mk, add -lpthread when linking runTest.exe using $FC=gfortran on LUMI/HIP #802
Otherwise the link was failing using gfortran
/opt/cray/pe/gcc/12.2.0/snos/bin/gfortran -o runTest.exe ./CPPProcess.o ./MatrixElementKernels.o ./BridgeKernels.o ./CrossSectionKernels.o ./CommonRandomNumberKernel.o ./RamboSamplingKernels.o ./testxxx.o  ./testmisc.o  ./runTest.o ./gCPPProcess.o ./gMatrixElementKernels.o ./gBridgeKernels.o ./gCrossSectionKernels.o ./gCommonRandomNumberKernel.o ./gRamboSamplingKernels.o ./testxxx_cu.o  ./testmisc_cu.o  ./runTest_cu.o -ldl -L../../lib -lmg5amc_common -L../../../../../test/googletest/install_gcc12.2.0/lib64/ -lgtest -lgtest_main -Xlinker -rpath='$ORIGIN/../../lib'   -lstdc++ -L/opt/rocm-5.2.3/llvm/bin/../../lib -lamdhip64
/usr/bin/ld: ../../../../../test/googletest/install_gcc12.2.0/lib64//libgtest.a(gtest-all.cc.o): undefined reference to symbol 'pthread_setspecific@@GLIBC_2.2.5'
/usr/bin/ld: /lib64/libpthread.so.0: error adding symbols: DSO missing from command line

I went back to gfortran because flang gives too many F90 errors on madevent #804