[jt774] in CODEGEN cudacpp.mk, backport form gg_tt.mad, add -lpthread when linking runTest.exe using $FC=gfortran on LUMI/HIP #802
Otherwise the link was failing using gfortran
/opt/cray/pe/gcc/12.2.0/snos/bin/gfortran -o runTest.exe ./CPPProcess.o ./MatrixElementKernels.o ./BridgeKernels.o ./CrossSectionKernels.o ./CommonRa>
/usr/bin/ld: ../../../../../test/googletest/install_gcc12.2.0/lib64//libgtest.a(gtest-all.cc.o): undefined reference to symbol 'pthread_setspecific@@>
/usr/bin/ld: /lib64/libpthread.so.0: error adding symbols: DSO missing from command line

I went back to gfortran because flang gives too many F90 errors on madevent #804