[oct23av] in eemumu mgOnGpuCxtypes.h, add missing function 'cxsmpl<float> operator*( const cxsmpl<float>& a, const double& b )' to fix eemumu float builds
ccache /usr/local/cuda-12.0/bin/nvcc -o build.none_f_inl0_hrd0/gcheck.exe build.none_f_inl0_hrd0/gcheck_sa.o -gencode arch=compute_70,code=compute_70 -gencode arch=compute_70,code=sm_70 -L../../lib/build.none_f_inl0_hrd0 -lmg5amc_common -Xlinker -rpath,'$ORIGIN/../../../lib/build.none_f_inl0_hrd0'  -L../../lib/build.none_f_inl0_hrd0 -lmg5amc_epem_mupmum_cuda build.none_f_inl0_hrd0/gCommonRandomNumberKernel.o build.none_f_inl0_hrd0/gRamboSamplingKernels.o build.none_f_inl0_hrd0/gCurandRandomNumberKernel.o -L/usr/local/cuda-12.0/lib64/ -lcurand
ccache g++  -O3  -std=c++17 -I. -I../../src -Wall -Wshadow -Wextra -ffast-math  -fopenmp -march=x86-64  -DMGONGPU_FPTYPE_FLOAT -DMGONGPU_FPTYPE2_FLOAT -fPIC -c CPPProcess.cc -o build.none_f_inl0_hrd0/CPPProcess.o
In file included from CPPProcess.cc:20:
../../src/HelAmps_sm.h: In function ‘void mg5amcCpu::FFV2_4_0(const fptype*, const fptype*, const fptype*, const fptype*, double, const fptype*, double, mgOnGpu::fptype*)’:
../../src/HelAmps_sm.h:1165:101: error: no match for ‘operator*’ (operand types are ‘const cxtype_sv’ {aka ‘const mgOnGpu::cxsmpl<float>’} and ‘const double’)
 1165 |     ( *vertex ) = ( -one ) * ( Ccoeff2 * COUP2 * ( +cI * TMP1 + ( two * cI ) * TMP3 ) + cI * ( TMP1 * Ccoeff1 * COUP1 ) );
      |                                                                                                ~~~~ ^ ~~~~~~~
      |                                                                                                |      |
      |                                                                                                |      const double
      |                                                                                                const cxtype_sv {aka const mgOnGpu::cxsmpl<float>}