[vecsizeFIX] regenerate ggtt.mad after reverting three commits in https://github.com/mg5amcnlo/mg5amcnlo/pull/23
Not surprisingly, the build fails because of
coupl.inc:10:46:

   10 |       DOUBLE PRECISION G, ALL_G(VECSIZE_MEMMAX)
      |                                              1
Error: Symbol ‘vecsize_memmax’ at (1) has no IMPLICIT type