[heft] remove mass and helicity arguments from the sxxxx call for EFT gg>h (#351) - better, but build still fails
../../src/HelAmps_heft.h: In instantiation of ‘void mg5amcCpu::VVS3_0(const fptype*, const fptype*, const fptype*, mgOnGpu::cxtype, mgOnGpu::fptype*) [with W_ACCESS = KernelAccessWavefunctions<false>; A_ACCESS = KernelAccessAmplitudes<false>; mgOnGpu::fptype = double; mgOnGpu::cxtype = mgOnGpu::cxsmpl]’:
CPPProcess.cc:163:101:   required from here
../../src/HelAmps_heft.h:822:76: error: conversion from ‘fptype_sv’ {aka ‘__vector(4) double’} to non-scalar type ‘const cxtype_sv’ {aka ‘const mgOnGpu::cxtype_v’} requested
  822 |     const cxtype_sv TMP3 = ( P1[0] * P2[0] - P1[1] * P2[1] - P1[2] * P2[2] - P1[3] * P2[3] );
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~