[refactorMakefile] in gg_tt.mad, improve dependency on discretesampler.mod in Source/makefile
Without this fix, the following situation could take place:

1. When make is interrupted by ctrl-c, DiscreteSampler.o exists but discretesampler.mod does not exist

make[1]: Entering directory '/data/avalassi/GPU2023/madgraph4gpuX/epochX/cudacpp/gg_tt.mad/Source'
AVX=none
RNDGEN=hasCurand
gfortran -I. -fPIC -w -ffixed-line-length-132 -O3 -ffast-math -fbounds-check -c StringCast.f -o StringCast.o
gfortran -I. -fPIC -w -ffixed-line-length-132 -O3 -ffast-math -fbounds-check -c DiscreteSampler.f -o DiscreteSampler.o
gfortran -I. -fPIC -w -ffixed-line-length-132 -O3 -ffast-math -fbounds-check -c dsample.f -o dsample.o
^Cmake: *** [../../Source/.timestamp_guard] Deleting file '../../Source/discretesampler.mod'
make: *** [makefile:65: ../../Source/.timestamp_guard] Interrupt

2. When make (or make -j) is then attempted, discretesampler.mod does not exist and cannot be recreated

make[1]: Entering directory '/data/avalassi/GPU2023/madgraph4gpuX/epochX/cudacpp/gg_tt.mad/Source'
AVX=none
RNDGEN=hasCurand
gfortran -I. -fPIC -w -ffixed-line-length-132 -O3 -ffast-math -fbounds-check -c dsample.f -o dsample.o
dsample.f:1090:10:

 1090 |       use DiscreteSampler
      |          1
Fatal Error: Cannot open module file ‘discretesampler.mod’ for reading at (1): No such file or directory
compilation terminated.