[susy2] in susyggtt.sa Parameters.h, fix mdl_G__exp__2 as in SM ggtt.sa (why is this different here??)
Replace
      constexpr cxsmpl<double> mdl_G__exp__2 = ( ( G ) * ( G ) );
by
      const fptype_sv mdl_G__exp__2 = ( ( G ) * ( G ) );

Cherry-pick commit 36dfe0591c31b27488c5f140042e88771b259e81 from Mon Apr 3 14:09:36 2023 +0200, fix a conflict with HIP support PR
Change the date with 'git commit --amend --date="$(date -R)"'
The above comments come from the original commit.

Updates on 14-Feb-2024 below.

'make HRDCOD=1' fails with
ccache /usr/local/cuda-12.0/bin/nvcc   -Xcompiler -O3 -lineinfo -I. -I../../src -I/usr/local/cuda-12.0/include/ -DUSE_NVTX -gencode arch=compute_70,code=compute_70 -gencode arch=compute_70,code=sm_70 -use_fast_math -std=c++17  -ccbin /cvmfs/sft.cern.ch/lcg/releases/gcc/12.1.0-57c96/x86_64-centos9/bin/g++ -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -DMGONGPU_HARDCODE_PARAM -Xcompiler -fPIC -c -x cu Parameters_MSSM_SLHA2.cc -o Parameters_MSSM_SLHA2_cu.o
Parameters_MSSM_SLHA2.h(333): error: expression must have a constant value
Parameters_MSSM_SLHA2.h(333): note #2703-D: cannot call non-constexpr function "atan(double) noexcept(true)"
/usr/local/cuda-12.0/include/crt/math_functions.h(4137): here
Parameters_MSSM_SLHA2.h(748): error: expression must have a constant value
Parameters_MSSM_SLHA2.h(748): note #2703-D: cannot call non-constexpr function "cos(double) noexcept(true)"
/usr/local/cuda-12.0/include/crt/math_functions.h(553): here
Parameters_MSSM_SLHA2.h(749): error: expression must have a constant value
Parameters_MSSM_SLHA2.h(749): note #2703-D: cannot call non-constexpr function "sin(double) noexcept(true)"
/usr/local/cuda-12.0/include/crt/math_functions.h(520): here
3 errors detected in the compilation of "Parameters_MSSM_SLHA2.cc".

Note however that 'CUDA_HOME=none make HRDCOD=1 -j' does succeed!
This means that constexpr sin, cos, atan exist in gcc but not in nvcc?
Maybe they can be simply hardcoded for nvcc as they are for gcc?
Also, check.exe succeeds, while runTest.exe fails because the reference logfile is missing.

Note also: cannot cherry-pick commit 586195dced571514e6f5f903c2e4b4b7fb7fe9af from Mon Apr 3 14:13:36 2023 +0200
This would result in an empty commit: I imagine that the upstream mg5anlo has modified this part of the generated code