[nobm/fpe] regenerate nobm_pp_ttW.mad after merging branch fpe with the fixes for #701
Now launching fails with a new build error (in cuda)
(this was later filed as #730 and fixed in a later commit of branch fpe)
HRDCOD=1 tlau/lauX.sh -CPP nobm_pp_ttW

            ccache /usr/local/cuda-12.0/bin/nvcc   -Xcompiler -fPIC -c -x cu Parameters_sm_no_b_mass.cc -o Parameters_sm_no_b_mass_cu.o
            In file included from Parameters_sm_no_b_mass.cc:15:
            Parameters_sm_no_b_mass.h:26:2: error: #error This non-SM physics process only supports MGONGPU_HARDCODE_PARAM builds (#439): please run "make HRDCOD=1"
               26 | #error This non-SM physics process only supports MGONGPU_HARDCODE_PARAM builds (#439): please run "make HRDCOD=1"
                  |  ^~~~~

Since I want to use CPP only, I retry disabling also CUDA:

CUDA_HOME=none HRDCOD=1 tlau/lauX.sh -CPP nobm_pp_ttW

And... this fixes the IEEE division by zero, but unfortunately it still finds other IEEE exceptions!

INFO: Running Survey
Creating Jobs
Working on SubProcesses
INFO:     P1_gu_ttxwpd
INFO: Building madevent in madevent_interface.py with 'CPP' matrix elements
INFO:     P1_gd_ttxwmu
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

In summary: the IEEE_DIVIDE_BY_ZERO part of #701 has been fixed, but not the other FPEs...

There are THREE IEEE FPEs still pending in pp_ttW.mad
 IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL