[shared] rerun eemumu, ggtt, ggttgg double/float - several issues
First, the scripts do not keep the errors, which are like
cmpExe /data/avalassi/GPU2020/madgraph4gpuX/epochX/cudacpp/gg_ttgg/SubProcesses/P1_Sigma_sm_gg_ttxgg/build.none_d_inl0_hrd0/gcheck.exe --common -p 2 64 2
cmpExe /data/avalassi/GPU2020/madgraph4gpuX/epochX/cudacpp/gg_ttgg/SubProcesses/P1_Sigma_sm_gg_ttxgg/build.none_d_inl0_hrd0/fgcheck.exe 2 64 2
terminate called after throwing an instance of 'std::runtime_error'
  what():  Bridge constructor: npar mismatch
Program received signal SIGABRT: Process abort signal.
Backtrace for this error:
        at /build/dkonst/CONTRIB/build/contrib/gcc-10.2.0/src/gcc/10.2.0/libstdc++-v3/libsupc++/vterminate.cc:95
        at /build/dkonst/CONTRIB/build/contrib/gcc-10.2.0/src/gcc/10.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:48
        at /build/dkonst/CONTRIB/build/contrib/gcc-10.2.0/src/gcc/10.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:58
        at /build/dkonst/CONTRIB/build/contrib/gcc-10.2.0/src/gcc/10.2.0/libstdc++-v3/libsupc++/eh_throw.cc:95
Avg ME (C++/CUDA)   = 6.626675e-04
Avg ME (F77/CUDA)   =
  File "<string>", line 1
    me1=6.626675e-04; me2=; reldif=abs((me2-me1)/me1); print('Relative difference =', reldif); ok = reldif <= 1E-5; print ( '%s (relative difference %s 1E-5)' % ( ('OK','<=') if ok else ('ERROR','>') ) )
                          ^
SyntaxError: invalid syntax

Second, those errors themselves need to be fixed

And possibly more to be fixed