[susy2] in susyggtt.sa Parameters.h, fix constexpr fixes for Majorana particles in HRDCOD=1
Cherry-pick commit bd5db8fcee5d9c7940fab36962de40651d37ebc3 from Mon Apr 3 14:06:20 2023 +0200, fix conflicts with HIP support PR
Change the date with 'git commit --amend --date="$(date -R)"'
The above comments come from the original commit.

Updates on 14-Feb-2024 below.

'make HRDCOD=1' fails with
ccache /cvmfs/sft.cern.ch/lcg/releases/gcc/12.1.0-57c96/x86_64-centos9/bin/g++  -O3  -std=c++17 -I.  -fPIC -Wall -Wshadow -Wextra -ffast-math  -fopenmp  -march=skylake-avx512 -mprefer-vector-width=256  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -DMGONGPU_HARDCODE_PARAM -fPIC -c Parameters_MSSM_SLHA2.cc -o Parameters_MSSM_SLHA2.o
In file included from Parameters_MSSM_SLHA2.cc:15:
Parameters_MSSM_SLHA2.h: In function 'const mg5amcCpu::Parameters_MSSM_SLHA2_dependentCouplings::DependentCouplings_sv mg5amcCpu::Parameters_MSSM_SLHA2_dependentCouplings::computeDependentCouplings_fromG(const mg5amcCpu::fptype_sv&)':
Parameters_MSSM_SLHA2.h:839:58: error: conversion from 'mg5amcCpu::fptype_sv' {aka '__vector(4) double'} to non-scalar type 'const mgOnGpu::cxsmpl<double>' requested
  839 |         constexpr cxsmpl<double> mdl_G__exp__2 = ( ( G ) * ( G ) );
      |                                                  ~~~~~~~~^~~~~~~~~
Parameters_MSSM_SLHA2.h:839:58: error: could not convert '(((mg5amcCpu::fptype_sv)G) * ((mg5amcCpu::fptype_sv)G))' from 'mg5amcCpu::fptype_sv' {aka '__vector(4) double'} to 'const mgOnGpu::cxsmpl<double>'
  839 |         constexpr cxsmpl<double> mdl_G__exp__2 = ( ( G ) * ( G ) );
      |                                                  ~~~~~~~~^~~~~~~~~
      |                                                          |
      |                                                          mg5amcCpu::fptype_sv {aka __vector(4) double}