[hack_ihel5] CODEGEN: in CPPProcess.cc add a warning that HRDCOD=1 is no longer supported on HIP (This was tested on LUMI for ggtt)
The ihel5 code builds but fails at runtime with "Cannot create GlobalVar Obj for symbol: _ZN9mg5amcGpuL5dcIPDE"
For comparison, the same code builds and runs successfully on CUDA

Fixing this on HIP may require enabling RDC via -fgpu-rdc
I added this flag to the compiler options but the link then failed with "undefined reference to __hip_fatbin"
This is complex to fix because linking of HIP executables is presently done with fortran in CUDACPP
I tried to switch to linking with hipcc (and even added --hip-link) but errors persisted at buildtime or runtime
** Since HRDCOD=1 is a non-default seldom-used option, I find it appropriate to declare it as unsupported on HIP **