Removing the -code flag builds the code but gets back the error. This is a debug. The issues is in constant memory chel?
u00u4okc9nudCQpFyr357@dgx0180:~/avMG/madgraph4gpu/examples/gpu/eemumu_AV/SubProcesses/P1_Sigma_sm_epem_mupmum$ cuda-memcheck --report-api-errors all ./check.exe -p 2048 256 12
========= CUDA-MEMCHECK
========= Program hit cudaErrorInvalidSymbol (error 13) due to "invalid device symbol" on CUDA API call to cudaMemcpyToSymbol.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x391b13]
=========     Host Frame:./check.exe [0x4662c]
=========     Host Frame:./check.exe [0x80e3]
=========     Host Frame:./check.exe [0x661b]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xe7) [0x21b97]
=========     Host Frame:./check.exe [0x7c1a]
=========
========= Program hit cudaErrorInvalidSymbol (error 13) due to "invalid device symbol" on CUDA API call to cudaMemcpyToSymbol.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x391b13]
=========     Host Frame:./check.exe [0x4662c]
=========     Host Frame:./check.exe [0x84ea]
=========     Host Frame:./check.exe [0x66a6]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xe7) [0x21b97]
=========     Host Frame:./check.exe [0x7c1a]
=========
========= Program hit cudaErrorInvalidSymbol (error 13) due to "invalid device symbol" on CUDA API call to cudaMemcpyToSymbol.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x391b13]
=========     Host Frame:./check.exe [0x4662c]
=========     Host Frame:./check.exe [0x8506]
=========     Host Frame:./check.exe [0x66a6]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xe7) [0x21b97]
=========     Host Frame:./check.exe [0x7c1a]
=========
========= Program hit cudaErrorInvalidPtx (error 218) due to "a PTX JIT compilation failed" on CUDA API call to cudaLaunchKernel.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x391b13]
=========     Host Frame:./check.exe [0x5c5f5]
=========     Host Frame:./check.exe [0x830d]
=========     Host Frame:./check.exe [0x6cdb]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xe7) [0x21b97]
=========     Host Frame:./check.exe [0x7c1a]
=========
========= Program hit cudaErrorInvalidPtx (error 218) due to "a PTX JIT compilation failed" on CUDA API call to cudaPeekAtLastError.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x391b13]
GPUassert: a PTX JIT compilation failed check_sa.cu 151
=========     Host Frame:./check.exe [0x57243]
=========     Host Frame:./check.exe [0x6b06]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xe7) [0x21b97]
=========     Host Frame:./check.exe [0x7c1a]
=========
check.exe: check_sa.cu:25: void gpuAssert3(cudaError_t, const char*, int, bool): Assertion `code == cudaSuccess' failed.
========= Error: process didn't terminate successfully
========= No CUDA-MEMCHECK results found