[hack] improve Zenny's patch by making it more general: use fptype_v{} instyead of fptype_v{0,0,0,} (Zenny) or fptype_v{0} (original code, which breaks nvc++)
The new code compiles for AVX=none and also AVX=avx2 on nvc++.
Cannot test if it runs because it fails the link (undefined reference to symbol '__sync_synchronize')