[susy2] in susyggtt.sa add constexpr to cxsmmpl::conj function (now valid code? In the past this failed as "a constexpr function cannot have a nonliteral return type mgOnGpu::cxsmpl")
Cherry-pick commit 0fd793b9630667768a303b32112f0c237920e6e5 from Mon Apr 3 13:55:33 2023 +0200, no conflicts
Change the date with 'git commit --amend --date="$(date -R)"'
The above comments come from the original commit.

Updates on 14-Feb-2024 below.

'make HRDCOD=1' fails with
ccache /cvmfs/sft.cern.ch/lcg/releases/gcc/12.1.0-57c96/x86_64-centos9/bin/g++  -O3  -std=c++17 -I.  -fPIC -Wall -Wshadow -Wextra -ffast-math  -fopenmp  -march=skylake-avx512 -mprefer-vector-width=256  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -DMGONGPU_HARDCODE_PARAM -fPIC -c Parameters_MSSM_SLHA2.cc -o Parameters_MSSM_SLHA2.o
In file included from Parameters_MSSM_SLHA2.cc:15:
Parameters_MSSM_SLHA2.h:758:5: error: expected unqualified-id before 'if'
  758 |     if( mdl_Mneu2 < 0 )
      |     ^~