[june24] revert the upgrade of mg5amcnlo to gpucpp_june24 because this fails codegen (#886)
Revert "[june24] upgrade mg5amcnlo from eef200f94 (in master_june24) to def7fa691 (gpucpp_june24)"
This reverts commit 54a6b45fcd421d36b8a29b20dccac53340688bf2.

Command "import /data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/TMPOUT/CODEGEN_mad_ee_mumu.mg" interrupted in sub-command:
"output madevent_simd ../TMPOUT/CODEGEN_mad_ee_mumu --hel_recycling=False --vector_size=32" with error:
AttributeError : 'SIMD_ProcessExporter' object has no attribute 'write_source_makefile'
Please report this bug on https://bugs.launchpad.net/mg5amcnlo
More information is found in 'MG5_debug'.
Please attach this file to your report.