[susy2] in susyggtt.sa, fix HRDCOD=0 cuda tests by including mdl_I51x11 in cIPD on device memory
'make HRDCOD=0' now succeeds and gives no warning.
Both CPU and GPU tests succeed in the combined runTest.exe.
Both check.exe and gcheck.exe succeed and give the same ME as each other.
(And they give the same ME as that from check.exe in 'CUDA_HOME make HRDCOD=1' if common random are used).

The other pending problem now is HRDCOD=1 builds in CUDA, where no constexpr sin/cos/atan are available.

Note: all tests so far were done with FPTYPE=d.
Builds with f and m precision still need to be fully tested and fixed.

'make HRDCOD=0 FPTYPE=f' builds fail:
ccache /cvmfs/sft.cern.ch/lcg/releases/gcc/12.1.0-57c96/x86_64-centos9/bin/g++  -O3  -std=c++17 -I.  -fPIC -Wall -Wshadow -Wextra -ffast-math  -fopenmp  -march=skylake-avx512 -mprefer-vector-width=256  -DMGONGPU_FPTYPE_FLOAT -DMGONGPU_FPTYPE2_FLOAT -fPIC -c Parameters_MSSM_SLHA2.cc -o Parameters_MSSM_SLHA2.o
In file included from Parameters_MSSM_SLHA2.cc:15:
Parameters_MSSM_SLHA2.h: In function 'const mg5amcCpu::Parameters_MSSM_SLHA2_dependentCouplings::DependentCouplings_sv mg5amcCpu::Parameters_MSSM_SLHA2_dependentCouplings::computeDependentCouplings_fromG(const mg5amcCpu::fptype_sv&, const mgOnGpu::fptype*)':
Parameters_MSSM_SLHA2.h:861:66: error: the value of 'G' is not usable in a constant expression
  861 |         constexpr cxsmpl<double> mdl_G__exp__2 = ( ( G ) * ( G ) );
      |                                                                  ^
Parameters_MSSM_SLHA2.h:857:23: note: 'G' was not initialized with a constant expression
  857 |         const fptype& G = G_sv[i];
      |                       ^