[jtmk] regenerate gg_tt.sa - no change, all as expected
There are a few more issues:
- 'make BACKEND=cuda' builds ok with HASCURAND=hasCurand
- 'make BACKEND=none' builds ok, but it has HASCURAND=hasNoCurand and this is wrong
- 'make bldcuda' fails, because it tries to build with HASCURAND=hasNoCurand

Specifically, the error is

make USEBUILDDIR=1 BACKEND=cuda -f makefile
make[1]: Entering directory '/data/avalassi/GPU2023/madgraph4gpuX/epochX/cudacpp/gg_tt.sa/SubProcesses/P1_Sigma_sm_gg_ttx'
BACKEND=cuda
makefile:181: HIP_HOME was not set: using ""
OMPFLAGS=-fopenmp
FPTYPE=d
HELINL=0
HRDCOD=0
HASCURAND=hasNoCurand
HASHIPRAND=hasNoHiprand
Building in BUILDDIR=build.cuda_d_inl0_hrd0 for tag=cuda_d_inl0_hrd0_hasNoCurand_hasNoHiprand (USEBUILDDIR is set = 1)
ccache /usr/local/cuda-12.0/bin/nvcc -o build.cuda_d_inl0_hrd0/gcheck.exe build.cuda_d_inl0_hrd0/check_sa_cu.o -gencode arch=compute_70,code=compute_70 -gencode arch=compute_70,code=sm_70 -L../../lib/build.cuda_d_inl0_hrd0 -lmg5amc_common -Xlinker -rpath='$ORIGIN/../../../lib/build.cuda_d_inl0_hrd0'  -L../../lib/build.cuda_d_inl0_hrd0 -lmg5amc_gg_ttx_cuda build.cuda_d_inl0_hrd0/CommonRandomNumberKernel_cu.o build.cuda_d_inl0_hrd0/RamboSamplingKernels_cu.o build.cuda_d_inl0_hrd0/CurandRandomNumberKernel_cu.o build.cuda_d_inl0_hrd0/HiprandRandomNumberKernel_cu.o
/usr/bin/ld: build.cuda_d_inl0_hrd0/CurandRandomNumberKernel_cu.o: in function `mg5amcGpu::CurandRandomNumberKernel::generateRnarray()':
tmpxft_0001c3cb_00000000-6_CurandRandomNumberKernel.cudafe1.cpp:(.text+0x22): undefined reference to `curandGenerateUniformDouble'

There are many issues here: first, curand is not found and it should; but also, we do not really need to export HASCURAND!