[shared] first draft implementation of stateful Bridge (#329) - build fails because of multiple definitions
ccache /usr/local/cuda-11.6/bin/nvcc -o runTest.exe ./CPPProcess.o ./RandomNumberKernels.o ./RamboSamplingKernels.o ./MatrixElementKernels.o ./BridgeKernels.o ./CrossSectionKernels.o ./fbridge.o ./testxxx.o  ./testmisc.o  ./runTest.o ./gCPPProcess.o ./gRandomNumberKernels.o ./gRamboSamplingKernels.o ./gMatrixElementKernels.o ./gBridgeKernels.o ./gCrossSectionKernels.o ./fbridge_cu.o ./testxxx_cu.o  ./testmisc_cu.o  ./runTest_cu.o -ldl -L../../lib -lmg5amc_common -L../../../../../test/googletest/build/lib/ -lgtest -lgtest_main -L/usr/local/cuda-11.6/lib64/ -lcurand  -lcuda -lgomp
/cvmfs/sft.cern.ch/lcg/releases/binutils/2.34-990b2/x86_64-centos7/bin/ld: ./fbridge_cu.o: in function `fbridgedelete_':
tmpxft_00004196_00000000-6_fbridge.cudafe1.cpp:(.text+0x10): multiple definition of `fbridgedelete_'; ./fbridge.o:fbridge.cc:(.text+0x0): first defined here
/cvmfs/sft.cern.ch/lcg/releases/binutils/2.34-990b2/x86_64-centos7/bin/ld: ./fbridge_cu.o: in function `fbridgesequence_':
tmpxft_00004196_00000000-6_fbridge.cudafe1.cpp:(.text+0x170): multiple definition of `fbridgesequence_'; ./fbridge.o:fbridge.cc:(.text+0x90): first defined here
/cvmfs/sft.cern.ch/lcg/releases/binutils/2.34-990b2/x86_64-centos7/bin/ld: ./fbridge_cu.o: in function `fbridgecreate_':
tmpxft_00004196_00000000-6_fbridge.cudafe1.cpp:(.text+0x3a0): multiple definition of `fbridgecreate_'; ./fbridge.o:fbridge.cc:(.text+0xf0): first defined here
collect2: error: ld returned 1 exit status